language: java

jdk:
- oraclejdk7
- oraclejdk8

deploy:
  provider: script
  script: mvn -Dmaven.test.skip=true -Prelease,gpg clean deploy --settings travis-settings.xml
  on:
    tags: true
    jdk: oraclejdk7

before_deploy:
  - openssl aes-256-cbc -K $encrypted_405d2016402c_key -iv $encrypted_405d2016402c_iv -in codesigning.asc.enc -out codesigning.asc -d
  - gpg --fast-import codesigning.asc

cache:
  directories:
    - $HOME/.m2
